### ISSUE TITLE
加上选择字体变大，完美

### ISSUE THREAD

**Issue by s3hengwu** [loperSeven/tablayout-ext#1]

**Comment by loper7** [comment]
字体变大还在斟酌如何实现较为妥当，会在后续更新中实现

**Comment by zaaach** [comment]
还有，可以设置某个tab是图标吗？

**Comment by loper7** [comment]
> 还有，可以设置某个tab是图标吗？

可以的呀，这个库是对tablayout的拓展，tablayout本身是可以设置图标的

**Comment by loper7** [comment]
0.1.1已支持修改选中状态和未选中状态字体设置
