### ISSUE TITLE
title 文字大小设置

### ISSUE THREAD

**Issue by JamieYee** [loperSeven/tablayout-ext#3]
![image](https://user-images.githubusercontent.com/15099278/106357038-a1e20b00-633e-11eb-8315-74d04bd2467b.png)
哥  像这样一个tab 有两种字体大小改如何设置呀

**Comment by loper7** [comment]
> ![image](https://user-images.githubusercontent.com/15099278/106357038-a1e20b00-633e-11eb-8315-74d04bd2467b.png)
> 哥 像这样一个tab 有两种字体大小改如何设置呀

这种需要用到自定义布局，上下两个textView，可以参考代码里面BaseText的实现方式，多加一个textView就可以了
